# Generated by Django 4.2.8 on 2024-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Childens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('rollnumber', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('atten', models.IntegerField(default='')),
                ('kannada', models.IntegerField(default='')),
                ('english', models.IntegerField(default='')),
                ('maths', models.IntegerField(default='')),
                ('science', models.IntegerField(default='')),
                ('social', models.IntegerField(default='')),
                ('total', models.IntegerField(default='')),
            ],
        ),
    ]
