# Generated by Django 4.2.8 on 2024-02-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childens',
            name='id',
        ),
        migrations.AlterField(
            model_name='childens',
            name='rollnumber',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
